In [36]:
import torch
import numpy as np

In [37]:
t1 = torch.rand(3,4)

In [38]:
t1

tensor([[0.8001, 0.6637, 0.1801, 0.5987],
        [0.0677, 0.0940, 0.4193, 0.3973],
        [0.9901, 0.2233, 0.1947, 0.3953]])

In [39]:
t2 = torch.rand(3,4)

In [40]:
t2

tensor([[0.4300, 0.7167, 0.7094, 0.7033],
        [0.7793, 0.6908, 0.3604, 0.3490],
        [0.8874, 0.8474, 0.4425, 0.7644]])

In [42]:
torch.cat((t1, t2), dim=0)

torch.Size([6, 4])

In [43]:
t2.ge(0)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.uint8)

In [44]:
t2.argmax(dim=0)

tensor([2, 2, 0, 2])

In [45]:
t2.numpy()

array([[0.4299894 , 0.7167346 , 0.70938534, 0.7032559 ],
       [0.7792637 , 0.69080126, 0.36042964, 0.34897506],
       [0.8873793 , 0.84736985, 0.44254398, 0.76441604]], dtype=float32)